# Site settings
title: Chowdown
email: your-email@domain.com
description: The plain text recipe database for hackers
baseurl: ""
twitter_username: clarklab
github_username:  clarklab

# Build settings
markdown: kramdown

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
