# Site settings
title: Chowdown
email: your-email@domain.com
description: The plain text recipe database for hackers
baseurl: "http://chowdown.io"
twitter_username: clarklab
github_username:  clarklab

# Build settings
markdown: kramdown

collections:
  components:
    output: true
  recipes:
    output: true

gems: ['jekyll-lunr-js-search']
    
mini_magick:
    thumbnail:
        source: images/_original
        destination: images/thumbnail
        resize: "400x400"
    medium:
        source: images/_original
        destination: images/medium
        resize: "1200x1200"
    large:
        source: images/_original
        destination: images/large
        resize: "2000x2000"